package com.qcws.shouna.model;

import io.jboot.db.annotation.Table;
import com.qcws.shouna.model.base.BaseCarouselImg;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "carousel_img", primaryKey = "id")
public class CarouselImg extends BaseCarouselImg<CarouselImg> {
	public static final CarouselImg dao = new CarouselImg().dao();
}
