package com.qcws.shouna.model;

import io.jboot.db.annotation.Table;
import com.qcws.shouna.model.base.BaseCustomerCashout;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "customer_cashout", primaryKey = "id")
public class CustomerCashout extends BaseCustomerCashout<CustomerCashout> {
	public static final CustomerCashout dao = new CustomerCashout().dao();
}
