package com.qcws.shouna.model;

import io.jboot.db.annotation.Table;
import com.qcws.shouna.model.base.BaseCustomerLevel;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "customer_level", primaryKey = "id")
public class CustomerLevel extends BaseCustomerLevel<CustomerLevel> {
	public static final CustomerLevel dao = new CustomerLevel().dao();
}
