package com.qcws.shouna.model;

import com.qcws.shouna.model.base.BaseCustomerBank;
import io.jboot.db.annotation.Table;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "customer_bank", primaryKey = "id")
public class CustomerBank extends BaseCustomerBank<CustomerBank> {
	public static final CustomerBank dao = new CustomerBank().dao();
}
