package com.qcws.shouna.model;

import com.qcws.shouna.model.base.BaseCustomerOrderOther;
import io.jboot.db.annotation.Table;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "customer_order_other", primaryKey = "id")
public class CustomerOrderOther extends BaseCustomerOrderOther<CustomerOrderOther> {
	public static final CustomerOrderOther dao = new CustomerOrderOther().dao();
}
