package com.qcws.shouna.model;

import io.jboot.db.annotation.Table;
import com.qcws.shouna.model.base.BaseCustomerAddress;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "customer_address", primaryKey = "id")
public class CustomerAddress extends BaseCustomerAddress<CustomerAddress> {
	public static final CustomerAddress dao = new CustomerAddress().dao();
}
