package com.qcws.shouna.model;

import io.jboot.db.annotation.Table;
import com.qcws.shouna.model.base.BaseCustomerInfo;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "customer_info", primaryKey = "id")
public class CustomerInfo extends BaseCustomerInfo<CustomerInfo> {
	public static final CustomerInfo dao = new CustomerInfo().dao();
}
