package com.qcws.shouna.model;

import io.jboot.db.annotation.Table;
import com.qcws.shouna.model.base.BaseCustomerCommission;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "customer_commission", primaryKey = "id")
public class CustomerCommission extends BaseCustomerCommission<CustomerCommission> {
	public static final CustomerCommission dao = new CustomerCommission().dao();
}
