package com.qcws.shouna.model;

import io.jboot.db.annotation.Table;
import com.qcws.shouna.model.base.BaseCustomerRecharge;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "customer_recharge", primaryKey = "id")
public class CustomerRecharge extends BaseCustomerRecharge<CustomerRecharge> {
	public static final CustomerRecharge dao = new CustomerRecharge().dao();
}
