package com.qcws.shouna.model;

import io.jboot.db.annotation.Table;
import com.qcws.shouna.model.base.BaseCustomerJoininfo;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "customer_joininfo", primaryKey = "id")
public class CustomerJoininfo extends BaseCustomerJoininfo<CustomerJoininfo> {
	public static final CustomerJoininfo dao = new CustomerJoininfo().dao();
}
