package com.qcws.shouna.model;

import io.jboot.db.annotation.Table;
import com.qcws.shouna.model.base.BaseItemArranger;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "item_arranger", primaryKey = "id")
public class ItemArranger extends BaseItemArranger<ItemArranger> {
	public static final ItemArranger dao = new ItemArranger().dao();
}
