package com.qcws.shouna.model;

import com.qcws.shouna.model.base.BaseItemComment;
import io.jboot.db.annotation.Table;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "item_comment", primaryKey = "id")
public class ItemComment extends BaseItemComment<ItemComment> {
	public static final ItemComment dao = new ItemComment().dao();
}
