package com.qcws.shouna.model;

import io.jboot.db.annotation.Table;
import com.qcws.shouna.model.base.BaseItemCourse;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "item_course", primaryKey = "id")
public class ItemCourse extends BaseItemCourse<ItemCourse> {
	public static final ItemCourse dao = new ItemCourse().dao();
}
