package com.qcws.shouna.model;

import io.jboot.db.annotation.Table;
import com.qcws.shouna.model.base.BaseItemInfo;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "item_info", primaryKey = "id")
public class ItemInfo extends BaseItemInfo<ItemInfo> {
	public static final ItemInfo dao = new ItemInfo().dao();
}
