package com.qcws.shouna.model;

import com.qcws.shouna.model.base.BaseShoppingCart;
import io.jboot.db.annotation.Table;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "t_shopping_cart", primaryKey = "id")
public class ShoppingCart extends BaseShoppingCart<ShoppingCart> {
	public static final ShoppingCart dao = new ShoppingCart().dao();
}
