package com.qcws.shouna.model;

import com.qcws.shouna.model.base.BaseShoppingReview;
import io.jboot.db.annotation.Table;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "t_refund_info", primaryKey = "id")
public class ShoppingReview extends BaseShoppingReview<ShoppingReview> {
	public static final ShoppingReview dao = new ShoppingReview().dao();
}
