package com.qcws.shouna.model;

import com.qcws.shouna.model.base.BaseShoppingOrderItem;
import io.jboot.db.annotation.Table;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "t_shop_order_item", primaryKey = "id")
public class ShoppingOrderItem extends BaseShoppingOrderItem<ShoppingOrderItem> {
	public static final ShoppingOrderItem dao = new ShoppingOrderItem().dao();
}
