package com.qcws.shouna.model;

import com.qcws.shouna.model.base.BaseShoppingOrder;
import io.jboot.db.annotation.Table;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "t_shopping_order", primaryKey = "id")
public class ShoppingOrder extends BaseShoppingOrder<ShoppingOrder> {
	public static final ShoppingOrder dao = new ShoppingOrder().dao();
}
