package com.qcws.shouna.model;

import io.jboot.db.annotation.Table;
import com.qcws.shouna.model.base.BaseSysArticle;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "sys_article", primaryKey = "id")
public class SysArticle extends BaseSysArticle<SysArticle> {
	public static final SysArticle dao = new SysArticle().dao();
}
