package com.qcws.shouna.model;

import io.jboot.db.annotation.Table;
import com.qcws.shouna.model.base.BaseSysOptLog;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "sys_opt_log", primaryKey = "id")
public class SysOptLog extends BaseSysOptLog<SysOptLog> {
	public static final SysOptLog dao = new SysOptLog().dao();
}
