package com.qcws.shouna.model;

import io.jboot.db.annotation.Table;
import com.qcws.shouna.model.base.BaseSysRole;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "sys_role", primaryKey = "id")
public class SysRole extends BaseSysRole<SysRole> {
	public static final SysRole dao = new SysRole().dao();
}
