package com.qcws.shouna.model;

import io.jboot.db.annotation.Table;
import com.qcws.shouna.model.base.BaseSysResourceGroup;

/**
 * Generated by Panda.
 */
@SuppressWarnings("serial")
@Table(tableName = "sys_resource_group", primaryKey = "id")
public class SysResourceGroup extends BaseSysResourceGroup<SysResourceGroup> {
	public static final SysResourceGroup dao = new SysResourceGroup().dao();
}
