package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysResourceGroup<M extends BaseSysResourceGroup<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

    /**
     * 标题
     */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 图标
	 */
	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}

    /**
     * 图标
     */
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	/**
	 * 排序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

    /**
     * 排序
     */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 父节点
	 */
	public void setPid(java.lang.Integer pid) {
		set("pid", pid);
	}

    /**
     * 父节点
     */
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

}
