package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysCity<M extends BaseSysCity<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 上门价格
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

    /**
     * 上门价格
     */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 服务率
	 */
	public void setOrderRate(java.math.BigDecimal orderRate) {
		set("order_rate", orderRate);
	}

    /**
     * 服务率
     */
	public java.math.BigDecimal getOrderRate() {
		return get("order_rate");
	}

	public void setEnglishName(java.lang.String englishName) {
		set("english_name", englishName);
	}

	public java.lang.String getEnglishName() {
		return getStr("english_name");
	}

}
