package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerLevel<M extends BaseCustomerLevel<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 等级标识
	 */
	public void setLevel(java.lang.Long level) {
		set("level", level);
	}

    /**
     * 等级标识
     */
	public java.lang.Long getLevel() {
		return getLong("level");
	}

	/**
	 * 等级名称
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

    /**
     * 等级名称
     */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 等级英文
	 */
	public void setTitleEn(java.lang.String titleEn) {
		set("title_en", titleEn);
	}

    /**
     * 等级英文
     */
	public java.lang.String getTitleEn() {
		return getStr("title_en");
	}

	/**
	 * 状态 0正常 1禁用
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}

    /**
     * 状态 0正常 1禁用
     */
	public java.lang.String getStatus() {
		return getStr("status");
	}

	/**
	 * 返佣率
	 */
	public void setOrderRate(java.math.BigDecimal orderRate) {
		set("order_rate", orderRate);
	}

    /**
     * 返佣率
     */
	public java.math.BigDecimal getOrderRate() {
		return get("order_rate");
	}

}
