package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysBankInfo<M extends BaseSysBankInfo<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 银行编码
	 */
	public void setBankCode(java.lang.String bankCode) {
		set("bank_code", bankCode);
	}

    /**
     * 银行编码
     */
	public java.lang.String getBankCode() {
		return getStr("bank_code");
	}

	/**
	 * 银行名称
	 */
	public void setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
	}

    /**
     * 银行名称
     */
	public java.lang.String getBankName() {
		return getStr("bank_name");
	}

	/**
	 * 银行img
	 */
	public void setBankImg(java.lang.String bankImg) {
		set("bank_img", bankImg);
	}

    /**
     * 银行img
     */
	public java.lang.String getBankImg() {
		return getStr("bank_img");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
