package com.qcws.shouna.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShoppingReview<M extends BaseShoppingReview<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 客户id
	 */
	public void setCustomerId(Integer customerId) {
		set("customer_id", customerId);
	}

    /**
     * 客户id
     */
	public Integer getCustomerId() {
		return getInt("customer_id");
	}


	/**
	 * 倒计时时间
	 */
	public void setCountdown(java.util.Date countdown) {
		set("countdown", countdown);
	}

    /**
     * 倒计时时间
     */
	public java.util.Date getCountdown() {
		return get("countdown");
	}

	/**
	 * 提交时间
	 */
	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

    /**
     * 提交时间
     */
	public java.util.Date getAddtime() {
		return get("addtime");
	}

	/**
	 * 结束时间
	 */
	public void setOvertime(java.util.Date overtime) {
		set("overtime", overtime);
	}

    /**
     * 结束时间
     */
	public java.util.Date getOvertime() {
		return get("overtime");
	}

	/**
	 * 退款原因
	 */
	public void setReason(String reason) {
		set("reason", reason);
	}

    /**
     * 退款原因
     */
	public String getReason() {
		return getStr("reason");
	}

	/**
	 * 审核结果  0  拒绝   1  通过
	 */
	public void setResult(String result) {
		set("result", result);
	}

	/**
	 * 审核结果  0  拒绝   1  通过
	 */
	public String getResult() {
		return getStr("result");
	}

	/**
	 * 审核说明
	 */
	public void setInstruction(String instruction) {
		set("instruction", instruction);
	}

	/**
	 * 审核说明
	 */
	public String getInstruction() {
		return getStr("instruction");
	}

    /**
     * 快递单号
     */
    public void setExNo(String exNo) {
        set("ex_no", exNo);
    }

    /**
     * 快递单号
     */
    public String getExNo() {
        return getStr("ex_no");
    }

	/**
	 * 订单号
	 */
	public void setOrderNo(String orderNo) {
		set("order_no", orderNo);
	}

	/**
	 * 订单号
	 */
	public String getOrderNo() {
		return getStr("order_no");
	}


}
