package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerOrder<M extends BaseCustomerOrder<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 客户id
	 */
	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

    /**
     * 客户id
     */
	public java.lang.Integer getCustomerId() {
		return getInt("customer_id");
	}

	/**
	 * 订单号
	 */
	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}

    /**
     * 订单号
     */
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	/**
	 * 项目id
	 */
	public void setItemId(java.lang.Integer itemId) {
		set("item_id", itemId);
	}

    /**
     * 项目id
     */
	public java.lang.Integer getItemId() {
		return getInt("item_id");
	}

	/**
	 * 项目名称
	 */
	public void setItemName(java.lang.String itemName) {
		set("item_name", itemName);
	}

    /**
     * 项目名称
     */
	public java.lang.String getItemName() {
		return getStr("item_name");
	}

	/**
	 * 价格
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

    /**
     * 价格
     */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 状态0.待支付 unpaid，1.待接单 wait 2.待上门 waitdoor 3.服务中 service 4.已完成 finish 5.退款订单 refund 6.待退款 remoney 7.退款成功 fefundsucess
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}

    /**
     * 状态0.待支付 unpaid，1.待接单 wait 2.待上门 waitdoor 3.服务中 service 4.已完成 finish 5.退款订单 refund 6.待退款 remoney 7.退款成功 fefundsucess
     */
	public java.lang.String getStatus() {
		return getStr("status");
	}

	/**
	 * 结算状态0待支付 1已支付
	 */
	public void setSettleStatus(java.lang.String settleStatus) {
		set("settle_status", settleStatus);
	}

    /**
     * 结算状态0待支付 1已支付
     */
	public java.lang.String getSettleStatus() {
		return getStr("settle_status");
	}

	/**
	 * 佣金
	 */
	public void setCommission(java.math.BigDecimal commission) {
		set("commission", commission);
	}

    /**
     * 佣金
     */
	public java.math.BigDecimal getCommission() {
		return get("commission");
	}

	/**
	 * 返点
	 */
	public void setOrderRate(java.math.BigDecimal orderRate) {
		set("order_rate", orderRate);
	}

    /**
     * 返点
     */
	public java.math.BigDecimal getOrderRate() {
		return get("order_rate");
	}

	/**
	 * 倒计时时间
	 */
	public void setCountdown(java.util.Date countdown) {
		set("countdown", countdown);
	}

    /**
     * 倒计时时间
     */
	public java.util.Date getCountdown() {
		return get("countdown");
	}

	/**
	 * 下单时间
	 */
	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

    /**
     * 下单时间
     */
	public java.util.Date getAddtime() {
		return get("addtime");
	}

	/**
	 * 结束时间
	 */
	public void setOvertime(java.util.Date overtime) {
		set("overtime", overtime);
	}

    /**
     * 结束时间
     */
	public java.util.Date getOvertime() {
		return get("overtime");
	}

	/**
	 * 退款金额
	 */
	public void setRefundAmount(java.math.BigDecimal refundAmount) {
		set("refund_amount", refundAmount);
	}

    /**
     * 退款金额
     */
	public java.math.BigDecimal getRefundAmount() {
		return get("refund_amount");
	}

	/**
	 * 电话号码
	 */
	public void setTelphone(java.lang.String telphone) {
		set("telphone", telphone);
	}

    /**
     * 电话号码
     */
	public java.lang.String getTelphone() {
		return getStr("telphone");
	}

	/**
	 * 省份
	 */
	public void setProvince(java.lang.String province) {
		set("province", province);
	}

    /**
     * 省份
     */
	public java.lang.String getProvince() {
		return getStr("province");
	}

	/**
	 * 城市
	 */
	public void setCity(java.lang.String city) {
		set("city", city);
	}

    /**
     * 城市
     */
	public java.lang.String getCity() {
		return getStr("city");
	}

	/**
	 * 预付款
	 */
	public void setAdvanceAmount(java.math.BigDecimal advanceAmount) {
		set("advance_amount", advanceAmount);
	}

    /**
     * 预付款
     */
	public java.math.BigDecimal getAdvanceAmount() {
		return get("advance_amount");
	}

	/**
	 * 尾款
	 */
	public void setFinalAmount(java.math.BigDecimal finalAmount) {
		set("final_amount", finalAmount);
	}

    /**
     * 尾款
     */
	public java.math.BigDecimal getFinalAmount() {
		return get("final_amount");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

    /**
     * 备注
     */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 到达状态0未上门 1已上门
	 */
	public void setReachStatus(java.lang.String reachStatus) {
		set("reach_status", reachStatus);
	}

    /**
     * 到达状态0未上门 1已上门
     */
	public java.lang.String getReachStatus() {
		return getStr("reach_status");
	}

	/**
	 * 定金


	 */
	public void setDeposit(java.math.BigDecimal deposit) {
		set("deposit", deposit);
	}

    /**
     * 定金


     */
	public java.math.BigDecimal getDeposit() {
		return get("deposit");
	}

}
