package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysResource<M extends BaseSysResource<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

    /**
     * 名称
     */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 图标
	 */
	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}

    /**
     * 图标
     */
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	/**
	 * 代码
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}

    /**
     * 代码
     */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 分组id
	 */
	public void setGroupId(java.lang.Integer groupId) {
		set("group_id", groupId);
	}

    /**
     * 分组id
     */
	public java.lang.Integer getGroupId() {
		return getInt("group_id");
	}

	/**
	 * 跳转地址
	 */
	public void setLinkUrl(java.lang.String linkUrl) {
		set("link_url", linkUrl);
	}

    /**
     * 跳转地址
     */
	public java.lang.String getLinkUrl() {
		return getStr("link_url");
	}

	/**
	 * 排序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

    /**
     * 排序
     */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

}
