package com.qcws.shouna.model.base;

import com.alibaba.fastjson.JSONArray;
import com.qcws.shouna.model.ItemComment;
import com.qcws.shouna.model.ItemCourse;
import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

import java.util.List;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseItemInfo<M extends BaseItemInfo<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 项目名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

    /**
     * 项目名称
     */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 项目代码
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}

    /**
     * 项目代码
     */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 0收纳 1课程
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}

    /**
     * 0收纳 1课程
     */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 项目说明
	 */
	public void setText(java.lang.String text) {
		set("text", text);
	}

    /**
     * 项目说明
     */
	public java.lang.String getText() {
		return getStr("text");
	}

	/**
	 * 适用人群
	 */
	public void setApplyPerson(java.lang.String applyPerson) {
		set("apply_person", applyPerson);
	}

    /**
     * 适用人群
     */
	public java.lang.String getApplyPerson() {
		return getStr("apply_person");
	}

	/**
	 * 价格
	 */
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

    /**
     * 价格
     */
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	/**
	 * 活动价格
	 */
	public void setSaleAmount(java.math.BigDecimal saleAmount) {
		set("sale_amount", saleAmount);
	}

    /**
     * 活动价格
     */
	public java.math.BigDecimal getSaleAmount() {
		return get("sale_amount");
	}

	/**
	 * 图片地址
	 */
	public void setImgurl(java.lang.String imgurl) {
		set("imgurl", imgurl);
	}

    /**
     * 图片地址
     */
	public java.lang.String getImgurl() {
		return getStr("imgurl");
	}

	/**
	 * 时间
	 */
	public void setTime(java.util.Date time) {
		set("time", time);
	}

    /**
     * 时间
     */
	public java.util.Date getTime() {
		return get("time");
	}

	/**
	 * 添加时间
	 */
	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

    /**
     * 添加时间
     */
	public java.util.Date getAddtime() {
		return get("addtime");
	}

	/**
	 * 结束时间
	 */
	public void setOvertime(java.util.Date overtime) {
		set("overtime", overtime);
	}

    /**
     * 结束时间
     */
	public java.util.Date getOvertime() {
		return get("overtime");
	}

	/**
	 * 排序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

    /**
     * 排序
     */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 分类id
	 */
	public void setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
	}

    /**
     * 分类id
     */
	public java.lang.Integer getCategoryId() {
		return getInt("category_id");
	}

	/**
	 * 是否推荐
	 */
	public void setIsRecommend(java.lang.String isRecommend) {
		set("is_recommend", isRecommend);
	}

    /**
     * 是否推荐
     */
	public java.lang.String getIsRecommend() {
		return getStr("is_recommend");
	}

	/**
	 * 天数
	 */
	public void setDayNum(java.lang.Long dayNum) {
		set("day_num", dayNum);
	}

    /**
     * 天数
     */
	public java.lang.Long getDayNum() {
		return getLong("day_num");
	}

	/**
	 * 分享图片
	 */
	public void setSharingurl(java.lang.String sharingurl) {
		set("sharingurl", sharingurl);
	}

    /**
     * 分享图片
     */
	public java.lang.String getSharingurl() {
		return getStr("sharingurl");
	}

	/**
	 * 直销返利比例
	 */
	public void setDirectRate(java.lang.Integer directRate) {
		set("direct_rate", directRate);
	}

	/**
	 * 直销返利比例
	 */
	public java.lang.Integer getDirectRate() {
		return getInt("direct_rate");
	}

	/**
	 * 合伙人一级返利比例
	 */
	public void setFirstPartnerRate(java.lang.Integer firstPartnerRate) {
		set("first_partner_rate", firstPartnerRate);
	}

	/**
	 * 合伙人一级返利比例
	 */
	public java.lang.Integer getFirstPartnerRate() {
		return getInt("first_partner_rate");
	}

	/**
	 * 合伙人二级返利比例
	 */
	public void setSecondPartnerRate(java.lang.Integer secondPartnerRate) {
		set("second_partner_rate", secondPartnerRate);
	}

	/**
	 * 合伙人二级返利比例
	 */
	public java.lang.Integer getSecondPartnerRate() {
		return getInt("second_partner_rate");
	}

	/**
	 * 加盟商一级返利比例
	 */
	public void setFirstFranchiseeRate(java.lang.Integer firstFranchiseeFat) {
		set("first_franchisee_rate", firstFranchiseeFat);
	}

	/**
	 * 加盟商一级返利比例
	 */
	public java.lang.Integer getFirstFranchiseeRate() {
		return getInt("first_franchisee_rate");
	}

	/**
	 * 加盟商二级返利比例
	 */
	public void setSecondFranchiseeRate(java.lang.Integer secondFranchiseeRate) {
		set("second_franchisee_rate", secondFranchiseeRate);
	}

	/**
	 * 加盟商二级返利比例
	 */
	public java.lang.Integer getSecondFranchiseeRate() {
		return getInt("second_franchisee_rate");
	}

	/**
	 * 视频课程地址
	 */
	public void setVideoUrl(java.lang.String videoUrl) {
		set("video_url", videoUrl);
	}

	/**
	 * 视频课程地址
	 */
	public java.lang.String getVideoUrl() {
		return getStr("video_url");
	}

	/**
	 * 是否是线下课程
	 */
	public void setIsUnder(java.lang.String isUnder) {
		set("is_under", isUnder);
	}

	/**
	 * 是否是线下课程
	 */
	public java.lang.String getIsUnder() {
		return getStr("is_under");
	}

	/**
	 * 商品颜色id
	 */
	public void setColorId(java.lang.Integer colorId) {
		set("color_id", colorId);
	}

	/**
	 * 商品颜色id
	 */
	public java.lang.Integer getColorId() {
		return getInt("color_id");
	}

	/**
	 * 商品大小id
	 */
	public void setSizeId(java.lang.Integer sizeId) {
		set("size_id", sizeId);
	}

	/**
	 * 商品大小id
	 */
	public java.lang.Integer getSizeId() {
		return getInt("size_id");
	}

	/**
	 * 卖出总数
	 */
	public Long sellNumber;

	/**
	 * 课程关联视频
	 */
	public List<ItemCourse> itemCourses;

	private List<ItemComment> comments;

	private JSONArray array;

	public Long getSellNumber() {
		return sellNumber;
	}

	public void setSellNumber(Long sellNumber) {
		this.sellNumber = sellNumber;
	}

	public List<ItemCourse> getItemCourses() {
		return itemCourses;
	}

	public void setItemCourses(List<ItemCourse> itemCourses) {
		this.itemCourses = itemCourses;
	}

	public List<ItemComment> getComments() {
		return comments;
	}

	public void setComments(List<ItemComment> comments) {
		this.comments = comments;
	}

	public JSONArray getArray() {
		return array;
	}

	public void setArray(JSONArray array) {
		this.array = array;
	}
}
