package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarouselImg<M extends BaseCarouselImg<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 轮播图地址
	 */
	public void setImg(java.lang.String img) {
		set("img", img);
	}

    /**
     * 轮播图地址
     */
	public java.lang.String getImg() {
		return getStr("img");
	}

	/**
	 * 添加时间
	 */
	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

    /**
     * 添加时间
     */
	public java.util.Date getAddtime() {
		return get("addtime");
	}

	/**
	 * 图片类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}

    /**
     * 图片类型
     */
	public java.lang.String getType() {
		return getStr("type");
	}

}
