package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysRole<M extends BaseSysRole<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

    /**
     * 名称
     */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 代码
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}

    /**
     * 代码
     */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 权限
	 */
	public void setPerms(java.lang.String perms) {
		set("perms", perms);
	}

    /**
     * 权限
     */
	public java.lang.String getPerms() {
		return getStr("perms");
	}

}
