package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysMessage<M extends BaseSysMessage<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}

    /**
     * 类型
     */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

    /**
     * 标题
     */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}

    /**
     * 内容
     */
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 插入时间
	 */
	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

    /**
     * 插入时间
     */
	public java.util.Date getAddtime() {
		return get("addtime");
	}

	/**
	 * 客户id
	 */
	public void setCustomerId(java.lang.Long customerId) {
		set("customer_id", customerId);
	}

    /**
     * 客户id
     */
	public java.lang.Long getCustomerId() {
		return getLong("customer_id");
	}

}
