package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysOptLog<M extends BaseSysOptLog<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 操作类型(login,operate)
	 */
	public void setOptType(java.lang.String optType) {
		set("optType", optType);
	}

    /**
     * 操作类型(login,operate)
     */
	public java.lang.String getOptType() {
		return getStr("optType");
	}

	/**
	 * 操作内容
	 */
	public void setOptContent(java.lang.String optContent) {
		set("optContent", optContent);
	}

    /**
     * 操作内容
     */
	public java.lang.String getOptContent() {
		return getStr("optContent");
	}

	/**
	 * ip地址
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

    /**
     * ip地址
     */
	public java.lang.String getIp() {
		return getStr("ip");
	}

	/**
	 * 操作时间
	 */
	public void setOptTime(java.util.Date optTime) {
		set("optTime", optTime);
	}

    /**
     * 操作时间
     */
	public java.util.Date getOptTime() {
		return get("optTime");
	}

	/**
	 * 操作人id
	 */
	public void setCusomerId(java.lang.Long cusomerId) {
		set("cusomer_id", cusomerId);
	}

    /**
     * 操作人id
     */
	public java.lang.Long getCusomerId() {
		return getLong("cusomer_id");
	}

}
