package com.qcws.shouna.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

import java.math.BigDecimal;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShoppingOrderItem<M extends BaseShoppingOrderItem<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 父订单id
	 */
	public void setOrderId(Integer orderId) {
		set("order_id", orderId);
	}

	/**
	 * 父订单id
	 */
	public Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 订单号
	 */
	public void setOrderNo(String orderNo) {
		set("order_no", orderNo);
	}

	/**
	 * 订单号
	 */
	public String getOrderNo() {
		return getStr("order_no");
	}

	/**
	 * 商品id
	 */
	public void setItemId(Integer itemId) {
		set("item_id", itemId);
	}

    /**
     * 商品id
     */
	public Integer getItemId() {
		return getInt("item_id");
	}


	/**
	 * 商品个数
	 */
	public void setItemNumber(Integer itemNumber) {
		set("item_number", itemNumber);
	}

	/**
	 * 商品个数
	 */
	public Integer getItemNumber() {
		return getInt("item_number");
	}

	/**
	 * 价格
	 */
	public void setPrice(BigDecimal price) {
		set("price", price);
	}

	/**
	 * 价格
	 */
	public BigDecimal getPrice() {
		return getBigDecimal("price");
	}


	/**
	 * 下单时间
	 */
	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

    /**
     * 下单时间
     */
	public java.util.Date getAddtime() {
		return get("addtime");
	}

	/**
	 * 客户id
	 */
	public void setCustomerId(Integer customerId) {
		set("customer_id", customerId);
	}

	/**
	 * 客户id
	 */
	public Integer getCustomerId() {
		return getInt("customer_id");
	}

	/**
	 * 状态  0 待支付   1 待发货  2 待收货  3 已完成  4 退款订单  5 待退款  6 退款成功  7 已取消
	 */
	public void setStatus(String status) {
		set("status", status);
	}

	/**
	 * 状态  0 待支付   1 待发货  2 待收货  3 已完成  4 退款订单  5 待退款  6 退款成功  7 已取消
	 */
	public String getStatus() {
		return getStr("status");
	}

	/**
	 * 结算状态0待支付 1已支付
	 */
	public void setSettleStatus(String settleStatus) {
		set("settle_status", settleStatus);
	}

	/**
	 * 结算状态0待支付 1已支付
	 */
	public String getSettleStatus() {
		return getStr("settle_status");
	}

	/**
	 * 倒计时时间
	 */
	public void setCountdown(java.util.Date countdown) {
		set("countdown", countdown);
	}

	/**
	 * 倒计时时间
	 */
	public java.util.Date getCountdown() {
		return get("countdown");
	}

	/**
	 * 结束时间
	 */
	public void setOvertime(java.util.Date overtime) {
		set("overtime", overtime);
	}

	/**
	 * 结束时间
	 */
	public java.util.Date getOvertime() {
		return get("overtime");
	}

	/**
	 * 退款金额
	 */
	public void setRefundAmount(java.math.BigDecimal refundAmount) {
		set("refund_amount", refundAmount);
	}

	/**
	 * 退款金额
	 */
	public java.math.BigDecimal getRefundAmount() {
		return get("refund_amount");
	}

	/**
	 * 收货地址id
	 */
	public void setAddressId(Integer addressId) {
		set("address_id", addressId);
	}

	/**
	 * 收货地址id
	 */
	public Integer getAddressId() {
		return getInt("address_id");
	}

	/**
	 * 电话号码
	 */
	public void setTelphone(String telphone) {
		set("telphone", telphone);
	}

	/**
	 * 电话号码
	 */
	public String getTelphone() {
		return getStr("telphone");
	}

	/**
	 * 省份
	 */
	public void setProvince(String province) {
		set("province", province);
	}

	/**
	 * 省份
	 */
	public String getProvince() {
		return getStr("province");
	}

	/**
	 * 城市
	 */
	public void setCity(String city) {
		set("city", city);
	}

	/**
	 * 城市
	 */
	public String getCity() {
		return getStr("city");
	}

	/**
	 * 备注
	 */
	public void setRemark(String remark) {
		set("remark", remark);
	}

	/**
	 * 备注
	 */
	public String getRemark() {
		return getStr("remark");
	}

	/**
	 * 是否直接购买    0  直接购买    1  购物车购买
	 */
	public void setType(String type) {
		set("type", type);
	}

	/**
	 * 是否直接购买    0  直接购买    1  购物车购买
	 */
	public String getType() {
		return getStr("type");
	}

	/**
	 * 发货快递单号
	 */
	public void setExNo(String exNo) {
		set("exNo", exNo);
	}

	/**
	 * 发货快递单号
	 */
	public String getExNo() {
		return getStr("exNo");
	}

}
