package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerOrderOther<M extends BaseCustomerOrderOther<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 使用人数
	 */
	public void setUserCount(java.lang.Integer userCount) {
		set("user_count", userCount);
	}

    /**
     * 使用人数
     */
	public java.lang.Integer getUserCount() {
		return getInt("user_count");
	}

	/**
	 * 衣橱大小
	 */
	public void setWardrobe(java.lang.String wardrobe) {
		set("wardrobe", wardrobe);
	}

    /**
     * 衣橱大小
     */
	public java.lang.String getWardrobe() {
		return getStr("wardrobe");
	}

	/**
	 * 收纳用品
	 */
	public void setStorge(java.lang.String storge) {
		set("storge", storge);
	}

    /**
     * 收纳用品
     */
	public java.lang.String getStorge() {
		return getStr("storge");
	}

	/**
	 * 衣橱图片
	 */
	public void setWardrobeImg(java.lang.String wardrobeImg) {
		set("wardrobeImg", wardrobeImg);
	}

    /**
     * 衣橱图片
     */
	public java.lang.String getWardrobeImg() {
		return getStr("wardrobeImg");
	}

	/**
	 * 需求说明
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

    /**
     * 需求说明
     */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 添加时间
	 */
	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

    /**
     * 添加时间
     */
	public java.util.Date getAddtime() {
		return get("addtime");
	}

	/**
	 * 订单id
	 */
	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}

    /**
     * 订单id
     */
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 上门时间
	 */
	public void setDoortime(java.util.Date doortime) {
		set("doortime", doortime);
	}

    /**
     * 上门时间
     */
	public java.util.Date getDoortime() {
		return get("doortime");
	}

	/**
	 * 地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}

    /**
     * 地址
     */
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 姓名
	 */
	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}

    /**
     * 姓名
     */
	public java.lang.String getRealname() {
		return getStr("realname");
	}

	/**
	 * 电话
	 */
	public void setTelphone(java.lang.String telphone) {
		set("telphone", telphone);
	}

    /**
     * 电话
     */
	public java.lang.String getTelphone() {
		return getStr("telphone");
	}

	/**
	 * 订单
	 */
	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}

    /**
     * 订单
     */
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

}
