package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerBank<M extends BaseCustomerBank<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 客户id
	 */
	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

    /**
     * 客户id
     */
	public java.lang.Integer getCustomerId() {
		return getInt("customer_id");
	}

	/**
	 * 户主姓名
	 */
	public void setAccountName(java.lang.String accountName) {
		set("account_name", accountName);
	}

    /**
     * 户主姓名
     */
	public java.lang.String getAccountName() {
		return getStr("account_name");
	}

	/**
	 * 卡号
	 */
	public void setCardNo(java.lang.String cardNo) {
		set("card_no", cardNo);
	}

    /**
     * 卡号
     */
	public java.lang.String getCardNo() {
		return getStr("card_no");
	}

	/**
	 * 电话号码
	 */
	public void setTelphone(java.lang.String telphone) {
		set("telphone", telphone);
	}

    /**
     * 电话号码
     */
	public java.lang.String getTelphone() {
		return getStr("telphone");
	}

	/**
	 * 银行名称
	 */
	public void setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
	}

    /**
     * 银行名称
     */
	public java.lang.String getBankName() {
		return getStr("bank_name");
	}

	/**
	 * 银行地址
	 */
	public void setBankAddress(java.lang.String bankAddress) {
		set("bank_address", bankAddress);
	}

    /**
     * 银行地址
     */
	public java.lang.String getBankAddress() {
		return getStr("bank_address");
	}

	/**
	 * 是否默认
	 */
	public void setIsDefault(java.lang.String isDefault) {
		set("is_default", isDefault);
	}

    /**
     * 是否默认
     */
	public java.lang.String getIsDefault() {
		return getStr("is_default");
	}

	/**
	 * 身份证号码
	 */
	public void setIdentity(java.lang.String identity) {
		set("identity", identity);
	}

    /**
     * 身份证号码
     */
	public java.lang.String getIdentity() {
		return getStr("identity");
	}

	/**
	 * 银行分行编号
	 */
	public void setBranch(java.lang.String branch) {
		set("branch", branch);
	}

    /**
     * 银行分行编号
     */
	public java.lang.String getBranch() {
		return getStr("branch");
	}

	/**
	 * 账户类型 1信用账户 2储蓄账户
	 */
	public void setAccountType(java.lang.Integer accountType) {
		set("account_type", accountType);
	}

    /**
     * 账户类型 1信用账户 2储蓄账户
     */
	public java.lang.Integer getAccountType() {
		return getInt("account_type");
	}

}
