package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysArticle<M extends BaseSysArticle<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

    /**
     * 标题
     */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}

    /**
     * 内容
     */
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 作者
	 */
	public void setAuthor(java.lang.String author) {
		set("author", author);
	}

    /**
     * 作者
     */
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	/**
	 * 添加时间
	 */
	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

    /**
     * 添加时间
     */
	public java.util.Date getAddtime() {
		return get("addtime");
	}

	/**
	 * 修改时间
	 */
	public void setLasttime(java.util.Date lasttime) {
		set("lasttime", lasttime);
	}

    /**
     * 修改时间
     */
	public java.util.Date getLasttime() {
		return get("lasttime");
	}

	/**
	 * 图片
	 */
	public void setImg(java.lang.String img) {
		set("img", img);
	}

    /**
     * 图片
     */
	public java.lang.String getImg() {
		return getStr("img");
	}

	/**
	 * 分类 url/article/img
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}

    /**
     * 分类 url/article/img
     */
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 分组
	 */
	public void setGroupCode(java.lang.String groupCode) {
		set("group_code", groupCode);
	}

    /**
     * 分组
     */
	public java.lang.String getGroupCode() {
		return getStr("group_code");
	}

}
