package com.qcws.shouna.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

import java.util.Date;


/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShoppingCart<M extends BaseShoppingCart<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 主键id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 商品id
	 */
	public void setItemId(java.lang.Integer itemId) {
		set("item_id", itemId);
	}

	/**
	 * 商品id
	 */
	public java.lang.Integer getItemId() {
		return getInt("item_id");
	}

	/**
	 * 用户id
	 */
	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

	/**
	 * 用户id
	 */
	public java.lang.Integer getCustomerId() {
		return getInt("customer_id");
	}

	/**
	 * 购买数量
	 */
	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}

	/**
	 * 购买数量
	 */
	public java.lang.Integer getNumber() {
		return getInt("number");
	}

	/**
	 * 添加时间
	 */
	public void setAddtime(java.util.Date addtime) {
		set("add_time", addtime);
	}

	/**
	 * 添加时间
	 */
	public java.util.Date getAddtime() {
		return get("add_time");
	}

}
