package com.qcws.shouna.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShoppingOrder<M extends BaseShoppingOrder<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 客户id
	 */
	public void setCustomerId(Integer customerId) {
		set("customer_id", customerId);
	}

    /**
     * 客户id
     */
	public Integer getCustomerId() {
		return getInt("customer_id");
	}

	/**
	 * 订单号
	 */
	public void setOrderNo(String orderNo) {
		set("order_no", orderNo);
	}

    /**
     * 订单号
     */
	public String getOrderNo() {
		return getStr("order_no");
	}

	/**
	 * 总价格
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

    /**
     * 总价格
     */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}


}
