package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseItemComment<M extends BaseItemComment<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 项目id
	 */
	public void setItemId(java.lang.Integer itemId) {
		set("item_id", itemId);
	}

    /**
     * 项目id
     */
	public java.lang.Integer getItemId() {
		return getInt("item_id");
	}

	/**
	 * 客户id
	 */
	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

    /**
     * 客户id
     */
	public java.lang.Integer getCustomerId() {
		return getInt("customer_id");
	}

	/**
	 * 订单id
	 */
	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}

    /**
     * 订单id
     */
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 标签
	 */
	public void setLable(java.lang.String lable) {
		set("lable", lable);
	}

    /**
     * 标签
     */
	public java.lang.String getLable() {
		return getStr("lable");
	}

	/**
	 * 评论内容
	 */
	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}

    /**
     * 评论内容
     */
	public java.lang.String getComment() {
		return getStr("comment");
	}

	/**
	 * 图片列表
	 */
	public void setImg(java.lang.String img) {
		set("img", img);
	}

    /**
     * 图片列表
     */
	public java.lang.String getImg() {
		return getStr("img");
	}

	/**
	 * 评价星级
	 */
	public void setStart(java.lang.String start) {
		set("start", start);
	}

    /**
     * 评价星级
     */
	public java.lang.String getStart() {
		return getStr("start");
	}

	/**
	 * 分数
	 */
	public void setScore(java.lang.Integer score) {
		set("score", score);
	}

    /**
     * 分数
     */
	public java.lang.Integer getScore() {
		return getInt("score");
	}

	/**
	 * 上级评论id
	 */
	public void setPid(java.lang.Integer pid) {
		set("pid", pid);
	}

    /**
     * 上级评论id
     */
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	/**
	 * 添加时间
	 */
	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

    /**
     * 添加时间
     */
	public java.util.Date getAddtime() {
		return get("addtime");
	}

	/**
	 * 项目名称
	 */
	public void setItemName(java.lang.String itemName) {
		set("item_name", itemName);
	}

    /**
     * 项目名称
     */
	public java.lang.String getItemName() {
		return getStr("item_name");
	}

	/**
	 * 整理师id
	 */
	public void setArrangerId(java.lang.Integer arrangerId) {
		set("arranger_id", arrangerId);
	}

    /**
     * 整理师id
     */
	public java.lang.Integer getArrangerId() {
		return getInt("arranger_id");
	}

}
