package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerAddress<M extends BaseCustomerAddress<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 姓名
	 */
	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}

    /**
     * 姓名
     */
	public java.lang.String getRealname() {
		return getStr("realname");
	}

	/**
	 * 手机号码
	 */
	public void setTelphone(java.lang.String telphone) {
		set("telphone", telphone);
	}

    /**
     * 手机号码
     */
	public java.lang.String getTelphone() {
		return getStr("telphone");
	}

	/**
	 * 地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}

    /**
     * 地址
     */
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 是否默认
	 */
	public void setIsDefault(java.lang.String isDefault) {
		set("is_default", isDefault);
	}

    /**
     * 是否默认
     */
	public java.lang.String getIsDefault() {
		return getStr("is_default");
	}

	/**
	 * 客户id
	 */
	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

    /**
     * 客户id
     */
	public java.lang.Integer getCustomerId() {
		return getInt("customer_id");
	}

	/**
	 * 省份
	 */
	public void setProvince(java.lang.String province) {
		set("province", province);
	}

    /**
     * 省份
     */
	public java.lang.String getProvince() {
		return getStr("province");
	}

	/**
	 * 城市
	 */
	public void setCity(java.lang.String city) {
		set("city", city);
	}

    /**
     * 城市
     */
	public java.lang.String getCity() {
		return getStr("city");
	}

}
