package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerBill<M extends BaseCustomerBill<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 客户id
	 */
	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

    /**
     * 客户id
     */
	public java.lang.Integer getCustomerId() {
		return getInt("customer_id");
	}

	/**
	 * 账单类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}

    /**
     * 账单类型
     */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 订单号
	 */
	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}

    /**
     * 订单号
     */
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	/**
	 * 代理层级
	 */
	public void setAgentLevel(java.lang.Integer agentLevel) {
		set("agent_level", agentLevel);
	}

    /**
     * 代理层级
     */
	public java.lang.Integer getAgentLevel() {
		return getInt("agent_level");
	}

	/**
	 * 交易说明
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}

    /**
     * 交易说明
     */
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 交易金额
	 */
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

    /**
     * 交易金额
     */
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	/**
	 * 余额
	 */
	public void setBalance(java.math.BigDecimal balance) {
		set("balance", balance);
	}

    /**
     * 余额
     */
	public java.math.BigDecimal getBalance() {
		return get("balance");
	}

	/**
	 * 添加时间
	 */
	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

    /**
     * 添加时间
     */
	public java.util.Date getAddtime() {
		return get("addtime");
	}

	/**
	 * 0扣款1进帐
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}

    /**
     * 0扣款1进帐
     */
	public java.lang.String getStatus() {
		return getStr("status");
	}

}
