package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerOrderEvaluate<M extends BaseCustomerOrderEvaluate<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 订单号
	 */
	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}

    /**
     * 订单号
     */
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	/**
	 * 整理师id
	 */
	public void setArrangerId(java.lang.Integer arrangerId) {
		set("arranger_id", arrangerId);
	}

    /**
     * 整理师id
     */
	public java.lang.Integer getArrangerId() {
		return getInt("arranger_id");
	}

	/**
	 * 姓名
	 */
	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}

    /**
     * 姓名
     */
	public java.lang.String getRealname() {
		return getStr("realname");
	}

	/**
	 * 1-5星
	 */
	public void setStar(java.lang.String star) {
		set("star", star);
	}

    /**
     * 1-5星
     */
	public java.lang.String getStar() {
		return getStr("star");
	}

	/**
	 * 分数
	 */
	public void setPoint(java.lang.String point) {
		set("point", point);
	}

    /**
     * 分数
     */
	public java.lang.String getPoint() {
		return getStr("point");
	}

	/**
	 * 说明
	 */
	public void setText(java.lang.String text) {
		set("text", text);
	}

    /**
     * 说明
     */
	public java.lang.String getText() {
		return getStr("text");
	}

	/**
	 * 添加时间
	 */
	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

    /**
     * 添加时间
     */
	public java.util.Date getAddtime() {
		return get("addtime");
	}

	/**
	 * 状态 0.空闲中 1.服务中
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}

    /**
     * 状态 0.空闲中 1.服务中
     */
	public java.lang.String getStatus() {
		return getStr("status");
	}

}
