package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerJoininfo<M extends BaseCustomerJoininfo<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 项目名称
	 */
	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}

    /**
     * 项目名称
     */
	public java.lang.String getRealname() {
		return getStr("realname");
	}

	/**
	 * 加盟项目
	 */
	public void setItemname(java.lang.String itemname) {
		set("itemname", itemname);
	}

    /**
     * 加盟项目
     */
	public java.lang.String getItemname() {
		return getStr("itemname");
	}

	/**
	 * 加盟说明
	 */
	public void setText(java.lang.String text) {
		set("text", text);
	}

    /**
     * 加盟说明
     */
	public java.lang.String getText() {
		return getStr("text");
	}

	/**
	 * 联系号码
	 */
	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

    /**
     * 联系号码
     */
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}

	/**
	 * 推荐人
	 */
	public void setRecommend(java.lang.String recommend) {
		set("recommend", recommend);
	}

    /**
     * 推荐人
     */
	public java.lang.String getRecommend() {
		return getStr("recommend");
	}

	/**
	 * 添加时间
	 */
	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

    /**
     * 添加时间
     */
	public java.util.Date getAddtime() {
		return get("addtime");
	}

}
