package com.qcws.shouna.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户名
	 */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}

    /**
     * 用户名
     */
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}

    /**
     * 密码
     */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 姓名
	 */
	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}

    /**
     * 姓名
     */
	public java.lang.String getRealname() {
		return getStr("realname");
	}

	/**
	 * 头像
	 */
	public void setHeadimg(java.lang.String headimg) {
		set("headimg", headimg);
	}

    /**
     * 头像
     */
	public java.lang.String getHeadimg() {
		return getStr("headimg");
	}

	/**
	 * 状态
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}

    /**
     * 状态
     */
	public java.lang.String getStatus() {
		return getStr("status");
	}

	/**
	 * 角色
	 */
	public void setRoles(java.lang.String roles) {
		set("roles", roles);
	}

    /**
     * 角色
     */
	public java.lang.String getRoles() {
		return getStr("roles");
	}

	public void setSecret(java.lang.String secret) {
		set("secret", secret);
	}

	public java.lang.String getSecret() {
		return getStr("secret");
	}

	/**
	 * 添加时间
	 */
	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

    /**
     * 添加时间
     */
	public java.util.Date getAddtime() {
		return get("addtime");
	}

	/**
	 * 最后登录时间
	 */
	public void setLogintime(java.util.Date logintime) {
		set("logintime", logintime);
	}

    /**
     * 最后登录时间
     */
	public java.util.Date getLogintime() {
		return get("logintime");
	}

	/**
	 * 最后登录ip
	 */
	public void setLoginip(java.lang.String loginip) {
		set("loginip", loginip);
	}

    /**
     * 最后登录ip
     */
	public java.lang.String getLoginip() {
		return getStr("loginip");
	}

}
